spring.application.name=project-spring
spring.datasource.url=jdbc:postgresql://localhost:5432/product-db
spring.datasource.username=postgres
spring.datasource.password=rnz

api.security.token.secret=${JWT_SECRET:my-secret-key}